services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  spring:
    image: challonsy/vote
    container_name: vote
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis